version: "3.9"

services:
  gitlab:
    container_name: gitlab-local
    image: gitlab/gitlab-ee:14.1.0-ee.0
    restart: always
    hostname: "localhost"
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "${GITLAB_HOST}"
        nginx['listen_port'] = 80
        alertmanager['admin_email'] = "${GITLAB_ADMIN_EMAIL}"
        gitlab_rails['initial_root_password'] = "${GITLAB_ROOT_PASSWORD}"
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        gitlab_rails['smtp_enable'] = "${SMTP_ENABLE}"
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = "${SMTP_PORT}"
        gitlab_rails['smtp_user_name'] = "${SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${SMTP_AUTHENTICATION}"
        gitlab_rails['smtp_enable_starttls_auto'] = "${SMTP_ENABLE_STARTTLS_AUTO}"
        gitlab_rails['smtp_tls'] = "${SMTP_TLS}"
        gitlab_rails['smtp_openssl_verify_mode'] = "${SMTP_OPENSSL_VERIFY_MODE}"
    volumes:
      - "${GITLAB_DIR}/config:/etc/gitlab"
      - "${GITLAB_DIR}/logs:/var/log/gitlab"
      - "${GITLAB_DIR}/data:/var/opt/gitlab"
